### PR TITLE
Add ApiURI for gitlab provider

### PR DESCRIPTION
**Pull request by julien-noblet**
It can let us use private server!

I currently use a self-hosted Gitlab server at work and I want to use this powerful package 😃.

Can you review my PR ?

### CODE REVIEW

**Comment by mouuff** [comment]
Amazing work! Can you add some coverage to it?

**Comment by julien-noblet** [comment]
> Amazing work! Can you add some coverage to it?

Sure! Is it enough?

**Comment by julien-noblet** [comment]
I'm testing it and there is an issue in downloading archives... 
I'm working on it!

Please wait before merge.

**Comment by mouuff** [comment]
Perfect, thank you for contributing!

**Pull request merged**
